# coding=utf-8
"""
用户常量
"""

# 用户状态
USER_STATUS_BAN_ACCOUNT = -100  # 账号封禁
USER_STATUS_BAN_CONTENT = -50  # 内容封禁
USER_STATUS_VISIBLE = 10  # 可见不推荐
USER_STATUS_REC = 20  # 推荐

# 用户状态信息
USER_STATUS_DICT = {
    USER_STATUS_VISIBLE: '可见不推荐',
    USER_STATUS_BAN_ACCOUNT: '账号封禁',
    USER_STATUS_BAN_CONTENT: '内容封禁',
}

# 用户能产生输出行为的状态
ALL_LEGAL_USER_STATUS = (
    USER_STATUS_VISIBLE, USER_STATUS_REC
)
# 用户不能产生输出行为的状态
ALL_ILLEGAL_USER_STATUS = (
    USER_STATUS_BAN_ACCOUNT, USER_STATUS_BAN_CONTENT
)

# 当前所有状态编码
ALL_VALID_USER_STATUS = set(USER_STATUS_DICT.keys())

# 注册来源
REG_SOURCE_INNER = 'inner'
REG_SOURCE_FACEBOOK = 'facebook'
REG_SOURCE_GOOGLE = 'google'
REG_SOURCE_WEIXIN = 'weixin'
ALL_REG_SOURCES = (REG_SOURCE_FACEBOOK, REG_SOURCE_GOOGLE, REG_SOURCE_INNER, REG_SOURCE_WEIXIN)

# 用户名类型
USER_NTYPE_ERR = 0
USER_NTYPE_PHONE = 1
USER_NTYPE_MAIL = 2
USER_NTYPE_INTER_PHONE = 3

# 用户平台
USER_PLATFORM_IOS = 1
USER_PLATFORM_ANDROID = 2

# 用户名称最长字段
USER_NAME_MAX_LEN = 200

# 用户搜索一页展示最大数目
USER_SEARCH_PAGE_PER_NUM = 20

# 用户标签
USER_TYPE_GUEST = 1  # 游客
USER_TYPE_NORMAL = 2  # 普通
USER_TYPE_VEST = 3  # 马甲
USER_TYPE_AUDITOR = 5  # 管理员

# 用户类型名称映射
USER_TYPE_DICT = {
    USER_TYPE_GUEST: '游客',
    USER_TYPE_NORMAL: '普通',
    USER_TYPE_VEST: '马甲',
    USER_TYPE_AUDITOR: '管理员',
}

# 登录来源
LOGIN_FROM_TYPE_PHONE = 1
LOGIN_FROM_TYPE_PC = 2

# 用户列表排序类型
USER_QUERY_SORT_REG = 1   # 最新
USER_QUERY_SORT_FANS = 2  # 粉丝数

# 注册频率限制
REGISTER_FREQUENCY_LIMIT_SEC = 5

# 登录状态
LOGIN_TYPE_GUEST = 0
LOGIN_TYPE_NORMAL = 1

# 机器人
SPIDER_ROB_ADMIN_SID = "60366f036c629c4da5178679"

