# -*- coding:utf-8 -*-


CODE_SUCCESS = 1  # 成功
CODE_FAILED = -1  # 失败

CODE_SESSION_ERROR = -11  # 登录验证失败

CODE_PERMISSION_FAILED = -100  # 权限验证失败
CODE_PERMISSION_GUEST_FAILED = -101  # 游客权限验证失败
CODE_PERMISSION_FORBIDDEN_FAILED = -102  # 封禁中不能进行此操作
CODE_NOT_FOUND = -104  # aka 404
CODE_FORBIDDEN_COUNTRY = -105
CODE_THIRD_ACCOUNT_AUTH_FAILED = -107  # 第三方账户验证失败
CODE_ACT_QUICKLY_ERROR = -108  # 操作过于频繁

CODE_PARAM_ERROR = -200  # 参数错误
CODE_VERSION_ERROR = -201  # 当前版本太低，请更新版本。

CODE_NAME_PASSWORD_ERROR = -1001  # 用户或密码错误
CODE_NAME_ALREADY_EXIST_ERROR = -1002  # 用户名已存在
CODE_NAME_STYLE_ERROR = -1003  # 用户名不为邮箱或手机号
CODE_VERIFICATION_CODE_ERROR = -1004  # 验证码错误
CODE_VERIFICATION_MAX_ERROR = -1005  # 验证码超过最大次数
CODE_NAME_EMPTY_ERROR = -1006  # 用户为空
CODE_NAME_NO_EXIST_ERROR = -1007  # 用户名不存在
CODE_NAME_FMT_ERROR = -1008  # 用户名格式错误
CODE_NICK_FMT_EMPTY_ERROR = -1009  # 昵称错误
CODE_NICK_FMT_EXIST_ERROR = -1010  # 昵称重复
CODE_NAME_OP_TYPE_ERROR = -1011    # 只支持创建平台/爬虫/马甲账户
CODE_NICK_TOO_SHORT_ERROR = -1012  # 昵称必须4个字符以上
CODE_REG_CREATE_QUICKLY_ERROR = -1013  # 注册频率过快
CODE_FORBIDDEN_USER_ERROR = -1014  # 此账户已封禁
CODE_NAME_OP_POST_COMMENT_TYPE_ERROR = -1015  # 只有平台/马甲账号才可以在后台发帖/评论
CODE_NICK_SENSITIVE_WORD_ERROR = -1016  # 昵称或签名不符合要求
CODE_AVATAR_FMT_ERROR = -1017  # 头像格式错误
CODE_BG_FMT_ERROR = -1018  # 背景格式错误
CODE_ACCOUNT_CREATE_ERROR = -1019  # 账户创建失败

CODE_PID_ERROR = -2009  # 帖子不存在
CODE_POST_EMPTY_ERROR = -2010  # 帖子内容为空
CODE_POST_CREATE_ERROR = -2011  # 帖子创建失败
CODE_POST_DELETE_AUTHOR_ERROR = -2012  # 该帖子只能由作者本人删除
CODE_POST_CREATE_QUICKLY_ERROR = -2013  # 创建帖子过快

CODE_CID_ERROR = -3009  # 评论不存在
CODE_COMMENT_EMPTY_ERROR = -3010  # 评论内容为空
CODE_COMMENT_CREATE_ERROR = -3011  # 评论创建失败
CODE_COMMENT_DELETE_AUTHOR_ERROR = -3012  # 该评论只能由作者本人删除
CODE_COMMENT_CREATE_QUICKLY_ERROR = -3013  # 创建评论过快

CODE_TID_ERROR = -4009  # 主题不存在
CODE_TAG_ALREADY_EXIST_ERROR = -4010  # 主题已存在
CODE_TAG_LIMIT_ERROR = -4011  # 最多添加3个主题
CODE_TAG_NAME_LEN_ERROR = -4012  # 标签文案长度错误

CODE_FAVOR_TIDS_MAX = -5001  # 达到关注主题上限
CODE_FAVOR_UIDS_MAX = -5002  # 达到关注用户上限


errmsg = {
    CODE_SUCCESS: 'Success',
    CODE_FAILED: 'Failed',

    CODE_SESSION_ERROR: 'Session error',

    CODE_PERMISSION_FAILED: '权限验证失败',
    CODE_PERMISSION_GUEST_FAILED: '游客不能进行此操作',
    CODE_PERMISSION_FORBIDDEN_FAILED: '封禁账户不能进行此操作',
    CODE_NOT_FOUND: '页面不存在',
    CODE_FORBIDDEN_COUNTRY: '您所在地区不能进行此操作',
    CODE_THIRD_ACCOUNT_AUTH_FAILED: '登录验证失败，建议更换登录账户',
    CODE_ACT_QUICKLY_ERROR: '操作过于频繁',

    CODE_PARAM_ERROR: '参数错误',
    CODE_VERSION_ERROR: '请更新版本',

    CODE_NAME_PASSWORD_ERROR: '手机号密码错误',
    CODE_NAME_ALREADY_EXIST_ERROR: '手机号已经存在',
    CODE_NAME_STYLE_ERROR: '需要用邮箱登录',
    CODE_VERIFICATION_CODE_ERROR: '验证码错误',
    CODE_VERIFICATION_MAX_ERROR: '到达单日验证码发送上限',
    CODE_NAME_EMPTY_ERROR: '手机号为空',
    CODE_NAME_NO_EXIST_ERROR: '手机号不存在',
    CODE_NAME_FMT_ERROR: '手机号格式错误',
    CODE_NICK_FMT_EMPTY_ERROR: '昵称为空',
    CODE_NICK_FMT_EXIST_ERROR: '昵称已经存在',
    CODE_NICK_TOO_SHORT_ERROR: '昵称太短',
    CODE_REG_CREATE_QUICKLY_ERROR: '登录过于频繁',
    CODE_FORBIDDEN_USER_ERROR: '账户已封禁',
    CODE_AVATAR_FMT_ERROR: '头像格式错误',
    CODE_BG_FMT_ERROR: '背景格式错误',
    CODE_ACCOUNT_CREATE_ERROR: '账户创建失败',

    CODE_TID_ERROR: '标签不存在',
    CODE_TAG_ALREADY_EXIST_ERROR: '标签已存在',
    CODE_TAG_LIMIT_ERROR: '使用标签过多',
    CODE_TAG_NAME_LEN_ERROR: '标签名称过长或过短',

    CODE_PID_ERROR: '帖子不存在',
    CODE_POST_EMPTY_ERROR: '帖子内容为空',
    CODE_POST_CREATE_ERROR: '创建帖子失败',
    CODE_POST_DELETE_AUTHOR_ERROR: '删除帖子失败',
    CODE_POST_CREATE_QUICKLY_ERROR: '创建帖子过于频繁',

    CODE_CID_ERROR: '评论不存在',
    CODE_COMMENT_EMPTY_ERROR: '评论内容为空',
    CODE_COMMENT_CREATE_ERROR: '创建评论失败',
    CODE_COMMENT_DELETE_AUTHOR_ERROR: '删除评论失败',
    CODE_COMMENT_CREATE_QUICKLY_ERROR: '创建评论过于频繁',

    CODE_FAVOR_TIDS_MAX: '已到达关注标签上限',
    CODE_FAVOR_UIDS_MAX: '已到达关注用户上限',


}
